// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuLqZS_rwgeRvTusMMIsFvcS7AP53_PYI',
    appId: '1:1008439320140:web:399f3ae652f29bb87c5ee9',
    messagingSenderId: '1008439320140',
    projectId: 'base-de-datos-diana-flutter',
    authDomain: 'base-de-datos-diana-flutter.firebaseapp.com',
    storageBucket: 'base-de-datos-diana-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Bhx2qCq4mvOfAeY8sJ5-Xz_i0qhC-HU',
    appId: '1:1008439320140:android:0a9be749797db6837c5ee9',
    messagingSenderId: '1008439320140',
    projectId: 'base-de-datos-diana-flutter',
    storageBucket: 'base-de-datos-diana-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVcrXXkAYLe2ZEZIn2uaDur8Lce2HOhQw',
    appId: '1:1008439320140:ios:df992fc519a6d4487c5ee9',
    messagingSenderId: '1008439320140',
    projectId: 'base-de-datos-diana-flutter',
    storageBucket: 'base-de-datos-diana-flutter.firebasestorage.app',
    iosBundleId: 'com.example.primerProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVcrXXkAYLe2ZEZIn2uaDur8Lce2HOhQw',
    appId: '1:1008439320140:ios:df992fc519a6d4487c5ee9',
    messagingSenderId: '1008439320140',
    projectId: 'base-de-datos-diana-flutter',
    storageBucket: 'base-de-datos-diana-flutter.firebasestorage.app',
    iosBundleId: 'com.example.primerProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuLqZS_rwgeRvTusMMIsFvcS7AP53_PYI',
    appId: '1:1008439320140:web:5b8e34fd0dce558b7c5ee9',
    messagingSenderId: '1008439320140',
    projectId: 'base-de-datos-diana-flutter',
    authDomain: 'base-de-datos-diana-flutter.firebaseapp.com',
    storageBucket: 'base-de-datos-diana-flutter.firebasestorage.app',
  );
}
